name: Build Docker and Push Registry

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  get-current-date:
    runs-on: ubuntu-latest
    steps:
      - name: get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
        
  build:
    runs-on: ubuntu-latest
    needs: get-current-date
    env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        GITHUB_SHA:  ${{github.sha}}    
        TAG_DATE: ${{ get-current-date.steps.date.outputs.date }}
        IMAGE_NAME: serfanrud/go-crud-food
    steps:
    - uses: actions/checkout@v3
    - name: docker-login
      shell: bash
      
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          
    - name: build docker image
      run: |
        echo image name is : $IMAGE_NAME $TAG_DATE
        docker build . --file dockerfile --tag $IMAGE_NAME:$TAG_DATE
        
    - name: docker push to registry
      run: |
        echo image name is : $IMAGE_NAME $TAG_DATE
        docker push $IMAGE_NAME:$TAG_DATE
